// Generated by delombok at Sat Jul 01 03:46:04 EEST 2017
package com.ontalsoft.flc.lib.chunks;

import java.io.IOException;
import com.ontalsoft.flc.lib.FLCChunk;
import com.ontalsoft.flc.lib.FLCFile;
import com.ontalsoft.flc.util.BinaryReader;

public class FLCChunkFrameType extends FLCChunk {
	private short chunks; // Number of subchunks
	private short delay; // Delay in milliseconds
	private short reserved; // Always zero
	private short width; // Frame width override (if non-zero)
	private short height; // Frame height override (if non-zero)

	public FLCChunkFrameType(FLCFile flcFile) {
		super(flcFile);
	}

	@Override
	protected void readChunk(BinaryReader reader) throws IOException {
		chunks = reader.readUInt16();
		delay = reader.readUInt16();
		reserved = reader.readInt16();
		width = reader.readUInt16();
		height = reader.readUInt16();
		readSubChunks(reader, chunks);
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public short getChunks() {
		return this.chunks;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public short getDelay() {
		return this.delay;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public short getReserved() {
		return this.reserved;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public short getWidth() {
		return this.width;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public short getHeight() {
		return this.height;
	}
}
